server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 123456

eureka:
  client:
    # 表示是否将自己作为服务注册进Eurekaserver。默认为true。
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓false|true，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      ### 当Eureka有多节点时：在defaultZone中配置所有的Eureka节点URL
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

      ### 当Eureka是单节点时：在defaultZone中配置单节点的Eureka的URL
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    # 服务名称修改（也就是将此服务在网页上Eurake面板“status”处的信息换成可读性高的名字）
    instance-id: payment8001
    # 在“status”处，将鼠标指针悬浮在payment8001，payment8002名下，会有IP地址提示
    prefer-ip-address: true

    ### 心跳检测与续约时间的相关设置：开发时应尽量设置的小些，保证服务挂掉后能被及时踢除
    # Eureka客户端发送心跳[包]的时间间隔（默认是30秒）
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳后的等待时间上限，单位为：秒（默认是90秒）。超时后，将立即踢除掉服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.lujun61.entity

# 异常信息解决：ashboardConfiguration$ProxyStreamServlet : Failed opening connection to http://localhost:8001/hystrix.stream?delay=2000 : 503 : HTTP/1.1 503
# 暴露全部的监控信息：让信息可以通过actuator回馈给dashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"