server:
  port: 8003

spring:
  application:
    name: cloud-payment-service-hystrix


eureka:
  client:
    # 表示是否将自己作为服务注册进Eurekaserver。默认为true。
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓false|true，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      ### 当Eureka是单节点时：在defaultZone中配置单节点的Eureka的URL
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    # 服务名称修改（也就是将此服务在网页上Eurake面板“status”处的信息换成可读性高的名字）
    instance-id: payment8003
    # 在“status”处，将鼠标指针悬浮在payment8001，payment8002名下，会有IP地址提示
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true