server:
  port: 8002

spring:
  application:
    ### 多个服务的名称name可以相同（重名服务）。重名服务使用【端口号】来进行区分
    name: cloud-payment-service
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 123456

eureka:
  client:
    # 表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      ### 多节点时：在defaultZone中配置所有的Eureka节点URL
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

      ### 单节点时：在defaultZone中配置单节点的Eureka的URL
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    # 服务名称修改（也就是将此服务在网页上Eurake面板“status”处的信息换成可读性高的名字）
    instance-id: payment8002
    # 在“status”处，将鼠标指针悬浮在payment8001，payment8002名下，会有IP地址提示
    prefer-ip-address: true

mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.lujun61.entity
